### ISSUE TITLE
Deploy kcp Using CRDB As the Backing Store

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#1022]
# Demo Objective
- [ ] `kcp` admin should be able to use CRDB as the backing store

# Demo Steps
1. Admin starts `kcp`, pointing `--etcd-servers` to a CRDB instance
1. User does <anything>
1. No user-facing changes, everyone is happy!

# Action Items

- [x] Identify upstream refactoring that is required for this to be generally painless to maintain
- [ ] Execute on upstream refactoring work
- [ ] Add CRDB client driver implementation to the `kcp-dev/kubernetes` fork in a next rebase

# Stories

- [ ] refactor `*etcd3.store{}` tests to accept `storage.Interface{}` https://github.com/kubernetes/kubernetes/issues/109831
- [ ] refactor `*etcd3.store{}` to use an interface for `etcd` interactions, documenting and clarifying `etcd` client semantics
- [ ] implement a CRDB version of the `etcd` client interface
- [ ] wire the CRDB-based implementation up to server options
- [ ] add the CRDB-based code to the `kcp-dev/kubernetes` fork
- [ ] add the CRDB-based options to `kcp` itself
- [ ] validate `kcp` on top of CRDB
