### ISSUE TITLE
Epic: Add support for quota

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1061]
# Demo Objective
- [x] Set quota in a namespace in a workspace and have the accounting only apply to content in that workspace+namespace
- [x] Make sure quota works correctly for built-in types
- [x] Make sure quota works correctly for normal CRs, especially when 2 different workspaces both define the same GroupResource
- [x] Make sure quota works correctly for bound CRs
- [x] Find a way to do quota for cluster-scoped resources e.g. namespaces
    - [x] https://github.com/kcp-dev/kubernetes/pull/97
    - [x] #1846 

====================== 0.6 cut line

- [X] ~APIExport owner can define quota for instances of APIResourceSchemas they own, and the quota is applied in the bound workspace~ not part of the quota implementation / not specific to quota; moving to separate issue if needed.
    - [X] ~A workspace owner with "cluster-admin" is not able to manipulate this quota~ not part of the quota implementation / not specific to quota; moved to #1840

# Stories
- [x] #1236 
- [x] Add support + e2e for quota for normal CRs
- [x] Add support + e2e for quota for bound CRs
- [x] Add support + e2e for quota for cluster-scoped resources

**Comment by maleck13** [comment]
So I think a key thing here is that a service offering an API can define how many of a certain object is allowed per workspace. I imagine this would happen when the APIBinding is created or possibly via an initializer if it is something that needs to be done for every workspace

**Comment by sttts** [comment]
In addition there must be authz that stops the admin user in the workspace to tweak the quota for the APIBinding objects. We at least need a plan for that, implementation can come later.

**Comment by sttts** [comment]
I completely miss a discussion about cluster scoped resources. Afaik Kube cannot restrict them at all. But we will need that. OpenShift has ClusterResourceQuota.

**Comment by ncdc** [comment]
> I completely miss a discussion about cluster scoped resources. Afaik Kube cannot restrict them at all. But we will need that. OpenShift has ClusterResourceQuota.

Recording for posterity (we've chatted about this but not written it here): ClusterResourceQuota lets you quota namespace-scoped resources per cluster (e.g. "only allow 10 ConfigMaps in the entire cluster"). It does not quota cluster-scoped resources.

https://docs.google.com/document/d/15LR7fecEwh0Fupo5m3Yh3rtGy81eEGSZhh8heHqttAQ/edit is a design document for a short-term approach for quota of cluster-scoped resources.

**Comment by ncdc** [comment]
Not yet. We need new epics/issues
