### ISSUE TITLE
Epic: User home workspaces

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1069]
# Introduction

We've been brainstorming the idea of replacing the current implementation of personal workspaces (+ pretty names) with user home workspaces. The current implementation has some shortcomings:

- Input doesn't necessarily equal output. When you request a personal workspace named "foo", if the parent workspace already has another workspace named "foo," the new workspace is named something like "foo-a7fje." If you run `kubectl workspace list`, you'll see "foo" even though underneath it has a different name.
- The duality created by ^ causes confusion because `kubectl get workspaces` and `kubectl workspace list` can show different sets of data
- There is a lot of of complex code (virtual workspace) to support personal workspaces in this manner. We could reduce complexity by using OOTB RBAC
- It's not easy to grant additional access to a personal workspace

One issue we've been struggling with is what is the starting point for a user coming to kcp? Assuming kcp is configured for OIDC, does a user have a "home organization" or anything like that? If we can say that it's a requirement for there to be a globally unique identifier per user, than we can say their starting workspace is a descendent of the `root:users:...` hierarchy.

# Demo Objective

Show that users can manage their own personal workspaces inside a their dedicated `Home` workspace. 

# Demo Steps

- [x] The user should be able to `kubectl get workspace '~'` in the root workspace, and this would trigger the creation of his own dedicated home workspace (something like `root:users:jd:jdoe`) and return the corresponding workspace resource when available and ready.
- [x] When the user home workspace is created on-the-fly (during first access), it will delay the CLI until the user home workspace is created (through some HTTP 429 "RetryAfter" response), and the initial request will be sent to the newly-created home workspace transparently.
- [x] The user is `cluster-admin` in his home workspace. By default he would create workspaces of Universal type in his home workspace.
- [x] We should allow any KCP shard to perform this on-the-fly creation of the user home workspace: we should not have to point to the shard that contains the bucket cluster workspace.  

=== Nice to have, but not the priority ===

- [x] CLI plugin support: Support the `kubectl ws ~` notation to go to switch to the home workspace, with the `kubectl ws` as an alias.
- [ ] ~Sharding integration: Integration in the front-proxy: the front-proxy should redirect to the shard that is expected to contains the bucket workspace in which in user home workspace take place.~ if we need more here, we will create a new issue

=== stretch goals for 0.6.0, very likely 0.7.0 ===

- [x] Allow users to create individual objects than workspaces at the home level
- [x] Allow multi-level workspace hierarchy inside the home workspace
- [ ] ~CLI plugin to enable sharing a personal workspace (workspace created under the home workspace), but just creating the expected RBAC.~ #1319

# Action Items

- [x] Scope the current demo as necessary to fit in prototype boundaries
- [x] []#1454
- [x] `workspaces` virtual workspace: Fix obsolete permission management to make it compatible with the Home workspaces -  PR merged: https://github.com/kcp-dev/kcp/pull/1374
- [x] `workspaces` virtual workspace: Fix ClusterWorkspaceType management to make it compatible with Home workspaces - merged PR: https://github.com/kcp-dev/kcp/pull/1414
- [x] #1243
- [x] Impersonation in workspaces virtual workspace SubjectAccessReview requests - PR: https://github.com/kcp-dev/kcp/pull/1456
- [x] Implement the http handler for the special `kubectl get workspace ~` request: it can return the home workspace definition even before it exists 
- [x] #1245
- [x] #1373 
  Follow-ups:
  - [x] https://github.com/kcp-dev/kcp/pull/1373#discussion_r916537993

====== up to here v0.6 ======

- [x] #1457
- [x] E2e tests
- [x] CLI plugin support - PR: https://github.com/kcp-dev/kcp/pull/1392
- [x] add home workspace flags (and probably disable by default)
- [x] doc and demo
 
=== stretch goal or 0.7.0 from here ===

**Comment by davidfestal** [comment]
Implementation brainstorming doc: https://docs.google.com/document/d/1C1PojxJMrvUc2BBeMg_uyXO-T-A79T-A8GnV1IwylWY/edit
