### ISSUE TITLE
Epic: API Export Permissions on Binding

### ISSUE THREAD

**Issue by shawn-hurley** [kcp-dev/kcp#1219]
# Demo Objective
- [x] Service provider should be able to ask for additional permissions when creating an API Export for when the API is bound
- [x] API Binding users must accept or deny the specific permissions when binding to the APIExport
- [x] When accepted and bound, the objects granted access should be projected into the APIExports virtual workspace.

# Demo Steps
1. Service Provider creates an APIExport but asks for permissions to a secrets
1. User binds to the API and accepts the permissions
1. Service provider can access the secret from the virtual workspace.

# Stories
 
- [x] #1221 
- [x] #1244
- [x] When accepting the permissions, the virtual workspace should now have access to watch/list those resources.

------ 0.6 cut line

- [x] #1632

------- 0.7 cut line

- [x] #1544
- [x] #1500

------- 0.7.1 cut line

- [x] Add e2e test cases https://github.com/kcp-dev/kcp/pull/1864
    - When an APIExport removes a permission claim, its apiexport virtual workspace no longer serves that resource
    - When an APIBinding changes an accepted claim to rejected, the apiexport virtual workspace no longer serves that resource (was: #1501)
    - When an APIBinding has not accepted a claim (it's neither accepted nor rejected), the apiexport virtual workspace does not include resources from the binding's workspace
- [x] 💣🔒 **APIExport VW should restrict for a given workspace based on bindings acceptance or rejection** fixed in main
- [x] **Pending/approval life-cycle in APIBindings**
  - [x] add `binding.status.exportPermissionClaims`

------- 0.8 cut line

- [ ] 💣🔒 **APIExport VW for a claim should not override MaximalPermissionPolicy of the owning APIExport of the resource (#1337)** @s-urbaniak 
    - [ ] @ncdc has an e2e ready to go for this, but it will fail until we fix it
- [ ] warning on entering a workspace if there are claims from an APIExport that have not yet been accepted/rejected in an APIBinding (inside of kubectl kcp) @nrb  https://github.com/kcp-dev/kcp/issues/1934

-------- MVP complete – testing-ready --------

  - [ ] `kubectl kcp apis bind | accept | reject` – sketch out a command @dinhxuanvu https://github.com/kcp-dev/kcp/issues/1935
- [ ] 🔒 **APIExport can add authorization and limit what a user can do in their own namespace using permission claims.** https://github.com/kcp-dev/kcp/issues/1840
- [ ] 🔒 **Add permissions: read, create, write, delete** https://github.com/kcp-dev/kcp/issues/1936
- [ ] Add object selection https://github.com/kcp-dev/kcp/issues/1937
  - [ ] **single object names**
  - [ ] by namespace
  - [ ] **by labels**
  - [ ] object reference selector (e.g. secrets referenced in PodSepc), maybe JSONPath
  - [ ] Adding regex pattern selector (on name or namespace)

**Comment by robinbobbitt** [comment]
@shawn-hurley the controller my team is building currently needs to be able to create a service account, cluster role, and cluster role bindings through the virtual workspace. Please let me know if you need additional detail. Thanks!

**Comment by pweil-** [comment]
@shawn-hurley 0.8 check in here.

*Demo objectives*
`Service provider should be able to ask for additional permissions when creating an API Export for when the API is bound` - I believe this can be checked off as complete.  The remaining tasks seem to be about limiting scope and security.  Correct?

*Stories*

are these scoped for delivery in 0.8?  If not can you update the description with expected delivery items?

* APIExport VW for a claim should not override MaximalPermissionPolicy of the owning APIExport of the resource (if that is the case, we need an e2e) 
* Pending/approval life-cycle in APIBindings

**Comment by pweil-** [comment]
cc @stevekuznetsov for 0.8 check in

**Comment by ncdc** [comment]
Moved #1337 to after 0.8. All claim-related work for 0.8 is now done. Moving epic milestone to v0.9

**Comment by ncdc** [comment]
> APIExport can add authorization and limit what a user can do in their own namespace using permission claims.

@sttts how is this different from the local MaximalPermissionPolicy?

**Comment by ncdc** [comment]
re
```
Add permissions: read, create, write, delete
Add object selection
 single object names
 by namespace
 by labels
 object reference selector (e.g. secrets referenced in PodSepc), maybe JSONPath
 Adding regex pattern selector (on name or namespace)
```

I'd say the most basic use case here is "API provider must only be allowed to see the resources it needs and no more", or to be more specific: "you can't see all my secrets" 😄.

**Comment by stevekuznetsov** [comment]
I've expanded on the remaining bullets here to create full issues and migrated this issue to a [project view](https://github.com/orgs/kcp-dev/projects/5/views/1).

**Comment by kylape** [comment]
@stevekuznetsov that link gives me a 404

**Comment by stevekuznetsov** [comment]
Updated link: https://github.com/orgs/kcp-dev/projects/1/views/31
