### ISSUE TITLE
 Rework downstream namespace names

### ISSUE THREAD

**Issue by jmprusi** [kcp-dev/kcp#1280]
# Introduction

We need to improve how the current downstream namespaces names are generated:

- Shorter namespace names, focus on not going over 32 chars (more chars causes issues with generated ingresses/routes as it hits 63 char limits)
- Have the workspace as part of the namespace name.
- Consistent/reproducible. 
- Allow the same k8s cluster to be added as multiple workloadClusters and multiple syncers.
- Avoid possible clashes with other namespaces.

Kubernetes Namespaces need to follow those requirements:
- Namespaces follow the [RFC 1123](https://tools.ietf.org/html/rfc1123) 
  - contain at most 63 characters
  - contain only lowercase alphanumeric characters or '-'
  - start with an alphanumeric character
  - end with an alphanumeric character

### The namespaceLocator struct

Currently the kcp syncer serialises in json some information on an annotation "" in the downstream namespace that contains:

- upstreamNamespace
- workspace

the changes introduced in https://github.com/kcp-dev/kcp/pull/1309 expand the annotation to include:

- upstreamNamespace
- workspace
- SyncTarget workspace
- SyncTarget Name
- SyncTarget UID

This information is used by the Spec Syncer and the Status Syncer to figure what namespace to use.

### The downstream Namespaces:

Previously the downstream namespaces were 59 characters long:

`kcp0124d7647eb6a00b1fcb6f2252201601634989dd79deb7375c373973`

After the PR:

`kcp-2r7hmup1y2r1`

This is done by hashing the namespaceLocator with `sha256.Sum224()`, convert the result to base36 and take 12 characters of the resulting string. 

This should unblock/fix some issues with external controllers adding the namespace to routes/ingresses.

### Spec Syncer

The Spec syncer is in charge of syncing down the KCP resources and creating if needed the downstream namespaces.

Before the PR https://github.com/kcp-dev/kcp/pull/1309 the syncer tried to create the downstream namespace by hashing the desired namespace locator, even if it existed before.

After the changes, the Spec Syncer tries to figure out if a downstream namespaces matches the desired namespacelocator (using the downstream informers). If that's the case it uses that namespace. If not, hashes the desired namespaceLocator and creates the downstream namespace.

The PR adds some basic conflict (namespace exists with different namespacelocator, etc)

### Status Syncer

The Status syncer is in charge of syncing upstream (KCP) the statuses of the downstream objects. To figure out where to sync up the status, it does it by looking into the namespaceLocator. This behaviour hasn't changed and remains the same. 

# Demo Objective

Improve the namespace generation in order to avoid conflicts in some cases while avoiding issues for ingress providers autogenerating hosts based on the namespace (too long).

# Demo Steps 

1. User creates a new namespace in a workspace that has a workloadcluster ready
3. Administrator can list the namespaces in the workloadcluster and recognise the ones created by KCP and be able to track their origins by the namespace name.
4. No noticeable changes for the user.

=== useful for local development / advanced scheduling cases === 
1. User creates a new workloadcluster named cluster1
1. User deploys the syncer for cluster1 in a Kind cluster
1. User creates a new workloadcluster named cluster2
1. User deploys the syncer for cluster2 in the same Kind cluster as previously
1. User creates a deployment and assigns it manually to the workloadcluster: cluster1 & cluster2, it should work without namespace conflicts. 

# Action Items

- [x] Scope the current demo as necessary to fit in prototype boundaries
- [x] Find the proper hashing algorithm to provide enough collision safety for 10k namespaces 
 ~~- [ ] Figure out the way to truncate long workspaces in a human readable way.~~
- [x] Make the syncers find the previously created namespace using downstream informers, instead of using the pattern to generate a new one.
- [x] Handle possibles conflicts.
- [x] Implement the logic into kcp 
- [x] namespace generation e2e tests
- [x] Contribute to final demo script and recording (Demo at community meeting https://github.com/kcp-dev/kcp/issues/1512)

# Related:

- closes https://github.com/kcp-dev/kcp/issues/1188
- https://github.com/kcp-dev/kcp/pull/1309
