### ISSUE TITLE
Epic: Scoping client calls in KCP

### ISSUE THREAD

**Issue by varshaprasad96** [kcp-dev/kcp#1490]
These are the places where client calls need to be modified to accept scoped contexts. For further changes which need to be done in each of these locations, refer: https://github.com/kcp-dev/kcp/pull/1376

======================== DONE - v0.8 =========================================
- [x] cluster-controller - https://github.com/kcp-dev/kcp/tree/main/cmd/cluster-controller
- [x] Ingress-controller - [cmd/ingress-controller](https://github.com/kcp-dev/kcp/tree/main/cmd/ingress-controller) - https://github.com/kcp-dev/kcp/pull/1817
- [x] Kcp-front-proxy - https://github.com/kcp-dev/kcp/tree/main/cmd/kcp-front-proxy - https://github.com/kcp-dev/kcp/pull/1819
- [x] pkg/reconciler 
     - [x] Apis
          - [x] Apibinding - https://github.com/kcp-dev/kcp/tree/main/pkg/reconciler/apis/apibinding (https://github.com/kcp-dev/kcp/pull/1569)
          - [x] Api_binding_deletion - [pkg/reconciler/apis/apibindingdeletion](https://github.com/kcp-dev/kcp/tree/main/pkg/reconciler/apis/apiexport) - (https://github.com/kcp-dev/kcp/pull/1569)
          - [x] Apiexport - https://github.com/kcp-dev/kcp/tree/main/pkg/reconciler/apis/apiexport
          - [x] apiresource - https://github.com/kcp-dev/kcp/tree/main/pkg/reconciler/apis/apibinding - https://github.com/kcp-dev/kcp/pull/1558
     - [x] Scheduling - https://github.com/kcp-dev/kcp/tree/main/pkg/reconciler/scheduling -  https://github.com/kcp-dev/kcp/pull/1578
     - [x] Tenancy - https://github.com/kcp-dev/kcp/tree/main/pkg/reconciler/scheduling -  https://github.com/kcp-dev/kcp/pull/1578
     - [x] workload - https://github.com/kcp-dev/kcp/tree/main/pkg/reconciler/scheduling - https://github.com/kcp-dev/kcp/pull/1578
- [x] [pkg/server](https://github.com/kcp-dev/kcp/tree/main/pkg/server) - https://github.com/kcp-dev/kcp/pull/1504
     - [x] workspaceController
     - [x] workspaceShardController
     - [x] workspaceTypeController
     - [x] organizationController
     - [x] teamController
     - [x] universalController
- [x] tests/e2e
     - [x] [Apibinding](https://github.com/kcp-dev/kcp/tree/main/test/e2e/apibinding) - https://github.com/kcp-dev/kcp/pull/1648
     - [x] [Authorizer](https://github.com/kcp-dev/kcp/tree/main/test/e2e/authorizer) - https://github.com/kcp-dev/kcp/pull/1648
     - [x] [Conformance](https://github.com/kcp-dev/kcp/tree/main/test/e2e/conformance) - https://github.com/kcp-dev/kcp/pull/1667
     - [x] [Fixtures](https://github.com/kcp-dev/kcp/tree/main/test/e2e/fixtures) - https://github.com/kcp-dev/kcp/pull/1732
     - [x] [Framework](https://github.com/kcp-dev/kcp/tree/main/test/e2e/framework) - https://github.com/kcp-dev/kcp/pull/1709
     - [x] [Reconciler](https://github.com/kcp-dev/kcp/tree/main/test/e2e/reconciler) - https://github.com/kcp-dev/kcp/pull/1677
     - [x] [Syncer](https://github.com/kcp-dev/kcp/tree/main/test/e2e/syncer) - https://github.com/kcp-dev/kcp/pull/1678
     - [x] [Virtual](https://github.com/kcp-dev/kcp/tree/main/test/e2e/virtual) - https://github.com/kcp-dev/kcp/pull/1707
     - [x] [Watchcache](https://github.com/kcp-dev/kcp/tree/main/test/e2e/watchcache) - https://github.com/kcp-dev/kcp/pull/1707
     - [x] [workspacetype](https://github.com/kcp-dev/kcp/tree/main/test/e2e/workspacetype) - https://github.com/kcp-dev/kcp/pull/1678

========================================TODO =========================================
- [ ] Front-proxy - https://github.com/kcp-dev/kcp/tree/main/cmd/sharded-test-server - https://github.com/kcp-dev/kcp/pull/1826
- [ ] Test-server - [cmd/test-server/kcp](https://github.com/kcp-dev/kcp/tree/main/cmd/sharded-test-server) - https://github.com/kcp-dev/kcp/pull/1826
- [ ] Virtual-workspaces - [cmd/virtual-workspaces](https://github.com/kcp-dev/kcp/tree/main/cmd/virtual-workspaces) - https://github.com/kcp-dev/kcp/pull/1826
- [ ] pkg/admission 
     - [ ] [Apibinding](https://github.com/kcp-dev/kcp/tree/main/pkg/admission/apibinding)
     - [ ] [pkg/admission/clusterworkspacetypeexists](https://github.com/kcp-dev/kcp/tree/main/pkg/admission/apibinding)
- [ ] pkg/authorization - https://github.com/kcp-dev/kcp/tree/main/pkg/admission/apibinding
- [ ] pkg/crdpuller - https://github.com/kcp-dev/kcp/tree/main/pkg/admission/apibinding
- [ ] pkg/localenvoy/controller/ingress - https://github.com/kcp-dev/kcp/tree/main/pkg/admission/apibinding
- [ ] pkg/metadata/dynamic - https://github.com/kcp-dev/kcp/tree/main/pkg/metadata
- [ ]  [pkg/virtual](https://github.com/kcp-dev/kcp/tree/main/pkg/virtual)
     - [x] apiexport
     - [x] framework
     - [x] Initializingworkspaces
     - [ ] Syncer
     - [ ] workspaces

**Comment by pweil-** [comment]
0.8 check in here.  Are all remaining items expected to land?  If not can we put a milestone breakdown the description?  Thanks!

**Comment by pweil-** [comment]
one more quick question, is this part of https://github.com/kcp-dev/kcp/issues/981?

**Comment by stevekuznetsov** [comment]
> one more quick question, is this part of https://github.com/kcp-dev/kcp/issues/981?
yes

**Comment by varshaprasad96** [comment]
> @varshaprasad96 what's your thought?

It maybe a bit difficult, but I'll make sure that at least the PRs are up for all.

**Comment by pweil-** [comment]
@varshaprasad96 no problem.  I think the description of the epic will be clear enough since this is the first pass.  My request to you is once you think you've finished what you can you make it obvious what was delivered in 0.8 so when we're looking at 0.9 release notes it's obvious.

Just something simple like `====== above delivered in 0.8, below in 0.9 =======` or similar.  I updated https://github.com/kcp-dev/kcp/issues/981 to reflect that it will continue in 0.9.

Thanks for all your work on this AND for breaking it into smaller PRs.  It looks like a beast to review if it was all in one.

**Comment by varshaprasad96** [comment]
@pweil- modified the description to reflect what has already been done. Based on the discussion with @stevekuznetsov, it was decided to put a hard stop on this particular epic by end of v0.8. Refactoring code right now is not effective as we can't replace the code-generator right away which is indirectly allowing PRs with older format to merge. It will be more efficient to remove the lister/informer generator dependency first, and then scope all the remaining clients at once disallowing the older formats.

**Comment by ncdc** [comment]
Brainstorming doc: https://docs.google.com/document/d/12RtZL9rnEYGYUjhkZbxc_qbXSuUFULuRXArpJvoqOo4/edit#heading=h.uts53tyl4jgs

See also: https://github.com/kcp-dev/apimachinery/pull/53

**Comment by stevekuznetsov** [comment]
This is now going to be tracked as parts of https://github.com/orgs/kcp-dev/projects/6/views/1?layout=board
