### ISSUE TITLE
Epic: Storage volumes placement

### ISSUE THREAD

**Issue by guymguym** [kcp-dev/kcp#1615]
# Demo Objective

- [ ] Admin sets up the control plane with several workload clusters in the same location, connected to the same shared network storage (e.g NFS server).
- [ ] User deploys an application that uses dynamic storage provisioning (e.g [DokuWiki helm chart](https://github.com/bitnami/charts/tree/master/bitnami/dokuwiki)).
- [ ] The application placement is relocated between clusters freely upon cluster failure or on demand with the storage volumes.

# Demo Steps

1. Admin setup shared NFS storage.
2. Admin setup workload clusters with NFS CSI provisioner.
3. Users deploying an application with PVC will sync to a workload cluster for dynamic provisioning.
4. Syncer will watch provisioned volume and sync up PV information to kcp.
5. Cluster failure triggers an update to workload placement.
6. Another workload cluster will sync the PVC+PV bound to each other (static provisioning mode) so that the migrated workload can start.

# Action Items 

- [ ] Scope the current demo as necessary to fit in prototype boundaries
- [ ] Contribute to final demo script and recording
- [ ] ..... TBD .....

# Stories

- [ ] Design where to store PV information in kcp - 4 options - PVC extended status, PVC annotations, PV structure, Custom CRD.
- [ ] Add storage controller to kcp.
- [ ] Add storage controller to syncer.
- [ ] Sync down PVC for dynamic provisioning.
- [ ] Syncer watch dynamic provisioned PVs and sync up PV information.
- [ ] Sync down bound PVC+PV for static provisioning.
- [ ] ..... TBD .....

Out of scope:
- RWO volumes - volume replication + workload quiesce.
- Placement with multiple Storage classes.
- Placement with multiple locations.

**Comment by pweil-** [comment]
I see we bumped this to 0.9.  Thanks for updating that.  @guymguym Quick question, is anything completing in 0.8 that we should update the description to reflect?  Specifically, the first story is Define & document new apis , is that going to land in the next 2 weeks before 0.8 closes?

**Comment by stevekuznetsov** [comment]
Are we expecting explicit user intent (via `Location`) to determine that failover is possible, or should the system understand compatibility based on the networking/PV availability?

**Comment by ncdc** [comment]
A `Location` is generally meant to act like a single cluster, i.e. workloads should be able to move among `SyncTargets` in a `Location`. This means networking and storage need to be fluid and compatible. There is also the idea of "cells" (xref #1622) that allows for a `Location` to be further subdivided, if you don't want to consider an entire `Location` to be 100% fluid.

**Comment by pweil-** [comment]
@guymguym 0.9 check in.  Are any of the stories listed out here expected to land for 0.9?

**Comment by cooktheryan** [comment]
@guymguym just wanted to bump this due to @pweil- ask

**Comment by davidfestal** [comment]
I don't think it will make it for 0.9

**Comment by davidfestal** [comment]
Only the first docs PR will be merged: https://github.com/kcp-dev/kcp/pull/1971

**Comment by ncdc** [comment]
Moved to v0.10
