### ISSUE TITLE
Epic: API evolution

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1671]
- [ ] Add fields to APIResourceSchema that contain CEL that is called during API version conversion
- [ ] Add CEL converter to apiextensions-apiserver
- [ ] Bound CRDs will need a way to point back at the actual CEL (annotation?)
- [ ] Conversions must go through a single hub version
- [ ] Feature gated

Demo:
- `kubectl apply` yaml with v1alpha1
- `kubectl get` returns v1alpha2, see results of conversion

**Comment by pweil-** [comment]
0.8 Check in here.  I don't see anything scoped per milestone, can we break down this epic more to see what is expected when?  Thanks!

**Comment by ncdc** [comment]
I started looking into this before my PTO. I will get it updated this week. Going to move to 0.9 for the time being.

/milestone v0.9

**Comment by ncdc** [comment]
Started some API brainstorming https://hackmd.io/_EnPemBUTF-b7WFs8o6Gjw

**Comment by stevekuznetsov** [comment]
This has been subsumed by https://github.com/kcp-dev/kcp/issues/2014 

/close
