### ISSUE TITLE
Use Structured Logging to Facilitate Better Observability

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#1694]
# Demo Objective
- [ ] Admin should be able to filter and query `kcp` logs to determine what actions were taken for a specific workspace, a specific object, or as a result of a specific event.
- [ ] End-to-end tests should filter & clarify the logs to provide a dev with only the pertinent logs on failure

# Demo Steps
1. Developer runs an end-to-end test that fails
1. Built-in code determines which logs are applicable and opens `lnav` to a focused view
1. Everyone is happy!

# Action Items

- [ ] Rebase onto 1.24
- [ ] Instrument our code with structured + contextual logging
- [ ] Add helpers to end-to-end tests

**Comment by stevekuznetsov** [comment]
Logging level suggestions from @sttts

- stopping/starting controller - V(0)
- enqueue key - V(2)
- dequeue key - V(4)
- per-key comments
  - processing - V(1)
  - client calls - V(2)
  - something not done - V(4)
- errors - logger.Error()

**Comment by stevekuznetsov** [comment]
For user-facing (terminal) logs, refer to @sttts experiments with [`zap`](https://github.com/sttts/kcp/commit/f2ee2d19084353819442bd78d60f823abff50493) and [`zerolog`](https://github.com/sttts/kcp/commit/1a4555e0403b3f8761f1faef0c276a8836a2c1a4)

**Comment by stevekuznetsov** [comment]
FWIW, finding items that need to be updated:

```
$ git grep -P 'klog(\.V\([0-9]+\))?\.(Info|Warning|Error)(f|S)?'
...
cmd/sharded-test-server/frontproxy.go:  klog.Infof("Waiting for kcp-front-proxy to be up")
cmd/sharded-test-server/frontproxy.go:                  klog.Errorf("Failed to create kcp client: %v", err)
cmd/sharded-test-server/frontproxy.go:                  klog.V(3).Infof("kcp-front-proxy not ready: %v", err)
...
```

**Comment by ncdc** [comment]
Ongoing work; moving to v0.11
