### ISSUE TITLE
Deploy KCP Proof-of-Concept on CRDB

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#1796]
# Demo Objective
- [ ] `kcp` should run with a CRDB backend

# Action Items

- [ ] land a refactor to `kcp-dev/kubernetes` that abstracts the client used by `*etcd3.store{}` based on work from Han [here](https://github.com/logicalhan/kubernetes/commit/334e4735758625f66ebd625886f3127507ac61b4)
- [ ] [async] upstream the refactor to `kubernetes/kubernetes`
- [ ] implement the interface with CRDB in `kcp-dev/kubernetes` based on work from Steve [here](https://github.com/stevekuznetsov/kubernetes/tree/skuznets/generic-storage)
- [ ] surface the options necessary to use this backend in `kcp`
- [ ] add a unit test and end-to-end suite using CRDB
- [ ] deploy an (unstable) `kcp` using this configuration to let it soak

/cc @pweil- @ncdc @sttts
