### ISSUE TITLE
epic: Multiple SyncTarget support and basic coordination controllers 

### ISSUE THREAD

**Issue by davidfestal** [kcp-dev/kcp#1898]
### Demo Objective

- [ ] Always consistently maintain syncer-specific views of KCP synced resources, when a resource is synced to several SyncTargets (either inside a location in specific cases, such a move of specific resources, or through several placement to several locations)
- [ ] Provide a way for coordination controllers to get the syncer-specific views of KCP syncer resources, especially status reported by the Syncer.
- [ ] Provide a way for coordination controllers to instruct transformations that should be applied by the syncer when syncing an resource downstream (at first through JsonPatch annotations, later on through more advanced transformation engines such as CEL definitions, driven by dedicated APIs).
- [ ] Provide a way for coordination controllers to instruct summarizing rules that should be applied by the syncer when syncing back a downstream resource downstream (at first just a Json annotation indicating if the syncer-specific status should be promoted to the main resource status. Later on more complete rules could be defined by dedicated APIs)
- [ ] Ensure the exclusiveness of coordination controllers on resources. only one coordination controller should be allowed to access a given coordinated resource in a workspace.

### Action Items

- [X] Scope of the current demo is necessary to fit in the prototype boundaries
- [ ] Contribute to the final demo script and recording

### Stories

- [ ] coordination controller support and demo
- [ ] Finish and merge Syncer virtual workspace transformations (and replace Syncer advanced scheduling feature by transformations)
- [ ] Reenable the splitter use-cases
