### ISSUE TITLE
epic: Split workloads code from control plane code

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#2410]
### Feature Description

Enhancement Link: https://github.com/kcp-dev/kcp/blob/main/docs/enhancements/0001_project_enhancements.md

See [this section](https://github.com/kcp-dev/kcp/blob/main/docs/enhancements/0001_project_enhancements.md#split-the-workloads-project-from-the-control-plane) for background.

### Stories

- [ ] [Create new workloads repository]()
- [ ] [Move source code]()
- [ ] [Ensure there is appropriate build/install documentation for workloads]()
- [ ] [Ensure there is appropriate CI coverage for workloads]()

### Proposed Solution

*

### Want to contribute?

- [ ] I would like to work on this issue.
