### ISSUE TITLE
✨ Rebase to Kubernetes 1.26

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#2772]
Links:
- [1.24 branch commit tracking spreadsheet](https://docs.google.com/spreadsheets/d/1pKfe1dICl65ST-r05MVwoc6nGDvUT0wTQ-rLcSfjPQo/edit#gid=0)
- [Pre-rebase prep branch](https://github.com/ncdc/kubernetes/tree/kcp-1.26-rebase-prep) (squashing as much as possible to minimize rebase effort; force-pushes will be frequent)

```[tasklist]
### Tasks
- [ ] https://github.com/kcp-dev/code-generator/pull/80
- [ ] Update our apimachinery to 1.26
- [ ] Update our client-go to 1.26
```

**Comment by ncdc** [comment]
apimachinery prep branch: https://github.com/kcp-dev/apimachinery/tree/1.26-prep

**Comment by ncdc** [comment]
client-go prep branch: https://github.com/kcp-dev/client-go/tree/1.26-prep

**Comment by nikhita** [comment]
This can now be closed, right?

cc @sttts

**Comment by xrstf** [comment]
This had been completed. We're now already on 1.28.
