### ISSUE TITLE
docs: broken links

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#2802]
```[tasklist]
### Tasks
- [ ] index.md: /developers
- [ ] CONTRIBUTING: LICENSE
- [ ] CONTRIBUTING: DCO
- [ ] CONTRIBUTING: https://docs.kcp.io/kcp/main/en/CONTRIBUTING/github.com/stretchr/testify/require (relative, not abs?)
- [ ] concepts/syncer.md: https://github.com/kcp-dev/kcp/tree/main/docs/architecture
- [ ] concepts/virtual-workspaces.md: pkg/virtual
```
