### ISSUE TITLE
Update all the TMC-related controller to use the cache informers where necessary

### ISSUE THREAD

**Issue by davidfestal** [kcp-dev/kcp#2900]
The various TMC-related controllers (called from `tmc/pkg/server/controllers.go`), for example for scheduling as well as SyncTarget API management, should use the cache informers for things like APIExports, SyncTargets, LogicalCluster resources.

It has been done on the TMC core side, everything is still TBD on the TMC side.

Here is a list of where changes should be done to use cache informers instead of shard-local informers:

- [workload_apiexport_controller.go](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/workload/apiexport/workload_apiexport_controller.go#L117) : local informers
- [apiexportcreate_controller.go](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/workload/apiexportcreate/apiexportcreate_controller.go#L130) : local informers
- [heartbeat_controller.go](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/workload/heartbeat/heartbeat_controller.go#L45) : local informers
- [namespace_controller.go](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/workload/namespace/namespace_controller.go#L114) : local informers
- [x] [placement_controller.go](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/workload/placement/placement_controller.go#L171) :
  - locations / synctargets: global informers
  - logicalclusters: should be removed / unused
  - others local informers
- [x] [resource_controller.go](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/workload/resource/resource_controller.go#L64) :
  - synctargets: global informer
  - others: local informers
- [x] [synctarget_controller.go](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/workload/synctarget/synctarget_controller.go#L50) :
  - workspaceshards: global informer
  - synctargets: local informer
- [x] [synctargetexports_controller.go](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/workload/synctargetexports/synctargetexports_controller.go#L150) :
  - apiexports / apiresourceschemas: global informers
  - other: local informers

**Comment by davidfestal** [comment]
PR https://github.com/kcp-dev/kcp/pull/2948 still needs to be merged in order to fix the issue
