### ISSUE TITLE
Global ingress support

### ISSUE THREAD

**Issue by davidfestal** [kcp-dev/kcp#2912]
### TL;DR

Implement a global ingress spanning several physical clusters than can be used with KCP workloads spread amonf several SyncTargets

### Progress tracking <a href="#progress-tracking" id="progress-tracking">#</a>

EPIC detailed issues and overall progress can be tracked with the following [project view](https://github.com/orgs/kcp-dev/projects/1/views/53)

### Stories

- [ ] Update the `kcp-glbc` repo codebase to the latest kcp version and dependencies 
- [ ] kcp-dev/kcp-glbc#502
- [ ] Allow bypassing the Route 53 requirement
