### ISSUE TITLE
epic: Kubernetes 1.27

### ISSUE THREAD

**Issue by xrstf** [kcp-dev/kcp#2986]
### Objective

This epic is about tracking the progress in updating kcp to Kubernetes 1.27. This follows the guide @ https://github.com/kcp-dev/kcp/blob/main/docs/content/developers/rebasing-kubernetes.md

### Action Items

```[tasklist]
- [ ] https://github.com/kcp-dev/apimachinery/pull/74
- [ ] https://github.com/kcp-dev/code-generator/pull/83
- [ ] https://github.com/kcp-dev/client-go/pull/28
- [ ] Update kcp-dev/kubernetes
- [ ] Update kcp-dev/kcp
```

**Comment by mjudeikis** [comment]
Created new one as now we moving towards 1.28: https://github.com/kcp-dev/kcp/issues/3003
