### ISSUE TITLE
epic: Kubernetes 1.28

### ISSUE THREAD

**Issue by mjudeikis** [kcp-dev/kcp#3003]
### Demo Objective

Objective
This epic is about tracking the progress in updating kcp to Kubernetes 1.28. This follows the guide @ https://github.com/kcp-dev/kcp/blob/main/docs/content/developers/rebasing-kubernetes.md

### Action Items

- [X] Scope of the current demo is necessary to fit in the prototype boundaries
- [ ] Contribute to the final demo script and recording

### Stories

- [x] Update apimachinery
- [x] Update code-generator
- [x] Update client-go
- [ ] update kubernetes
- [ ] update kcp
```[tasklist]
### Tasks
- [ ] https://github.com/kcp-dev/apimachinery/pull/76
- [ ] https://github.com/kcp-dev/code-generator/pull/84
- [ ] https://github.com/kcp-dev/client-go/pull/29
- [ ] https://github.com/kubernetes/kubernetes/pull/120202
```

**Comment by mjudeikis** [comment]
Kubernetes cherry-pick tracking:

- [ ] 019506716a2 (kcp/kcp-1.26-split) Switch genericcontrolplane/apis to frob system:admin
- [ ] 9b2bf8983e9 pkg/controller/resourcequota: nil out closed channels
- [ ] c2dc4bb4d7c UPSTREAM: <carry>: update kcp repo dependencies
- [ ] 37c22366c0c README
- [ ] c36229523d3 LICENSES
- [ ] ea0a4d6f8aa stuff
- [ ] 32777ecf7d0 go.mod
- [ ] 2fd83b5dcb9 client-go
- [ ] ced1452f1d0 serviceaccounts
- [ ] cfc41b37a3b registries
- [ ] 7b01a1c29e1 auth
- [ ] 9613d821282 pkg/controllers
- [ ] 0596c4658c6 kube-aggregator/openapi
- [ ] 6694ee05630 apiextensionsserver generated
- [ ] ca05ca81284 apiextensionsserver
- [ ] 199dd14369c admission
- [ ] ece23f2e61f apiserver/endpoints
- [ ] 5277c43574d apiserver/registry
- [ ] 4a91465e84b apiserver/storage
- [ ] 1556634c4e6 apiserver
- [ ] 42396947e52 generic controlplane
