### ISSUE TITLE
epic: Kubernetes 1.30

### ISSUE THREAD

**Issue by embik** [kcp-dev/kcp#3068]
### Demo Objective

Opening this to track upgrading kcp and the related forks we currently maintain to Kubernetes 1.30, released in December 2023.

A similar epic for 1.28 was #3003.

### Stories

- [x] Update apimachinery
- [x] Update code-generator
- [x] Update client-go
- [x] update kubernetes
- [ ] update kcp

```[tasklist]
### Pull Requests
- [ ] https://github.com/kcp-dev/apimachinery/pull/79
- [ ] https://github.com/kcp-dev/code-generator/pull/90
- [ ] https://github.com/kcp-dev/client-go/pull/37
```
