### ISSUE TITLE
Prototype Syncer Virtual APIServer

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#350]
Buld a Virtual APIServer that
- [ ] draft `ExternalSync`-related API types as described in https://docs.google.com/document/d/1k72fgGBNJzbY1Rkxj9_1WksHZR0cNT5OeadCpWuc-zM/edit#
- [ ] provides consistent list/watch over workspaces that are connected to a given location (pcluster)
- [ ] with only those resources visible the syncer is interested in
- [ ] applying lcd, gcd semantics (as chosen)
- [ ] with a mechanism to plug-in live, golang-based transformations (one-object-to-one-object) of objects in kcp
- [ ] with a mechanism to plug-in live, golang-based transformations that do 1:n mapping of an object in kcp to multiple objects to be synced.

**Comment by davidfestal** [comment]
This is an old issue, superseded by new epics like this one: https://github.com/kcp-dev/kcp/issues/1898.
Closing.
