### ISSUE TITLE
Prototype 3: API Author Demo

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#417]
# Demo Objective
Close over consumer details, evolve APIs

1. For ingress (shouldn’t ingress have a wildcard?)
1. For serving (reencrypt)
1. For talking to another service

# Demo Steps
1. Create new workspace for our new cert-manager API backend
1. Run cert-manager (as Deployment if possible, locally is also fine because not focus of this epic) with a kubeconfig of a kcp controller workspace.
1. Export the cert-manager APIs (those needed to issue a serving cert)
1. In another workspace, import the cert-manager APIs from above
1. Show webapp getting a certificate within the workspace
1. Stetch goal: **A compatible API schema change is deployed**
1. Stetch goal: **See the workspaces to see the new schema automatically**

# Action Items

- [x] Scope the current demo as necessary to fit in prototype boundaries
- [x] Create and link required tasks to realize demo
- [x] https://github.com/kcp-dev/kcp/pull/583 @sttts 
- [x] automatically install CRDs into Universal workspaces
- [x] Create APIBindingController: @ncdc #755
  - create a CRD from APIResourceSchema in shadow workspace
  - phase transitions of the APIBinding
  - follow-ups:
    - ~~[ ] set the storage versions in the APIBinding's status @ncdc~~ moved to https://github.com/kcp-dev/kcp/issues/842
    - [x] stop unbinding, only unbinding we want is deletion, see https://github.com/kcp-dev/kcp/pull/702/files#r830041070
    - [x] ~~replace CRDReady condition with Established, see https://github.com/kcp-dev/kcp/pull/702#discussion_r830022232~~
    - ~~[ ] have more speaking names of CRDs in shadow namespace, see https://github.com/kcp-dev/kcp/pull/702#discussion_r830045834~~ moved https://github.com/kcp-dev/kcp/issues/843
     - [x] consolodate system CRD installation in couple of post-start-hooks and by system CRD provider, see kcp-install-api-resource-controller
    - ~~[ ] add admission to only allow `apis.kcp.dev/bound-crd` annotation in `system:bound-crds` workspace https://github.com/kcp-dev/kubernetes/pull/48/files#r827736066~~ moved to https://github.com/kcp-dev/kcp/issues/844
    - ~~[ ]  stop CRDs and APIBindings to add the same GVRs~~ moved to https://github.com/kcp-dev/kcp/issues/748
    - ~~[ ] add rebinding incl. e2e~~ moved to https://github.com/kcp-dev/kcp/issues/845
- [x] https://github.com/kcp-dev/kcp/pull/732 ~~ Create APIExportController~~
   - ~~conditions, phases~~
   - ~~medium-term: prune status.boundResourceSchemas~~ 
- [x] APIBinding authorization check that the APIBinding user can access the APIExport objects (for workspace reference) @ncdc #653 
- [x] #755 Remove inheritFrom from ClusterWorkspaceSpec @ncdc
- [x] #755 Update apiextensions code in kcp & kubernetes to use APIBindings @ncdc 
- [x] https://github.com/kcp-dev/kcp/pull/763 Contribute to final demo script and recording
- ~~[ ] stretch-goal: admission preventing deletion of APIResourceSchemas that are bound~~
- [ ] **prototype4+**: Build APIExport virtual apiserver.
- [ ] ~~**prototype4+** 💣: CR Deletion~~ moved to https://github.com/kcp-dev/kcp/issues/846
- [ ] **prototype4+**: Write APIBinding admission to verify schema compatibility
- [ ] **prototype4+**: Write APIDeployment controller (which rolls out schema updates automatically to APIBindings)
- [ ] **prototype5+**: Write CEL-based migration mechanism as part of APIResourceSchema.

# Design Details

## API types
Create concrete API types following the sketches in https://docs.google.com/document/d/1k72fgGBNJzbY1Rkxj9_1WksHZR0cNT5OeadCpWuc-zM/edit:
  - `APIExport`
  - `APIBinding`
  - `APIResourceSchema`

## APIExportController
- Create/maintain a `system:kcp:exported-crds` (name TBD) workspace
- Each exported API schema turns into a uniquely named CRD in this workspace
- see https://docs.google.com/document/d/1MhfRk_VV5orvspx1OzU5De7nnE6va9lIpLUKBKnzuWE/edit#heading=h.gcx2dkxb3w1j

## APIBindingController
- TODO

## apiextensions updates
- Remove inheritFrom logic
- When listing/getting CRDs, combine what's in the current logical cluster with all CRDs associated with all APIBindings for the current workspace
- Deny creation of a CRD in a workspace if the same GVR exists coming from any APIBindings

## APIExport virtual apiserver

**Comment by pweil-** [comment]
Notes from discussion:

> evolve APIS

User can A) add a new api, b) deliver a forward compatible change to an existing api export

After this demo, a consumer who leverages these mechanisms will then be a source of input to the "api evolution" epic with additional requirements (i have people using it, i need a non forward change, and i want to do side by side of old api and new api)

**Comment by sttts** [comment]
Updated the steps:
- no app deployment
- new step with schema update

**Comment by fabianvf** [comment]
We've been working on making cert-manager multi-cluster aware, if anyone else is working on this issue feel free to reach out (fabianvf on kubernetes slack)

**Comment by ncdc** [comment]
@sttts I updated the description with more details & design info. PTAL. Can you clarify what "APIImport admission" and "APIDeployment controller" are?

**Comment by ncdc** [comment]
Status update:
- APIBinding admission is merged #653 
- #702 replaces clusterWorkspace.spec.inheritFrom entirely with APIBinding-based extensions
    - The implementation is mostly done. We probably can make changes in follow-up PRs
        - 1 thing that isn't finished / correct is setting the storage versions in the APIBinding's status
    - Not sure on the conditions & reasons I added. Could use a review. Some implementation details probably leak a bit too much.
    - Unit tests are in progress. Working to add more.
    - Replaced the api inheritance e2e with a new apibinding e2e. It tests basic functionality - just that binding works. Things related to testing more involved logic such as rebinding are in unit tests.

**Comment by sttts** [comment]
Moved everything to issues. Closing the epic for p3.
