### ISSUE TITLE
Multi-Release-Epic: Consume Compute via Transparent Multi Cluster set up in a different workspace

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#912]
# Demo Objective
- [ ] User should be able to be able to consume compute defined in a different workspace and potentially by a different person.

# Demo Steps

- [x] https://github.com/kcp-dev/kcp/pull/829 in org-admin role: create workspace N as negotiation domain (aka infrastructure workspace)
- [x] https://github.com/kcp-dev/kcp/pull/829 add WorkloadClusters to N
- [x] https://github.com/kcp-dev/kcp/pull/829 wait for negotiation
- [x] https://github.com/kcp-dev/kcp/pull/829 a `APIResourceSchema` named `<timestamp>.<resource>.<group>` 
- ~~[ ] and an `APIExport` are created by a controller~~ Moved to the admin's responsibility
- [x] https://github.com/kcp-dev/kcp/pull/829 create LocationDomain for that workspace in the org or root

=== switch to the user role ===

- [x] https://github.com/kcp-dev/kcp/pull/829 create a Universal workspace and see it getting the location pool assigned via the label `scheduling.kcp.dev/domain=<lcluster>:<location-pool-name>`
- [x] https://github.com/kcp-dev/kcp/pull/829 the user does not know about workload clusters. 
  The user can discover LocationDomain in the org or the root: `kubectl get LocationDomains` and `kubectl get locations`.
- [x] https://github.com/kcp-dev/kcp/pull/829 observe the location scheduler scheduling namespaces to locations from the domain by setting the `scheduling.kcp.dev/placement` annotation with one location (random).
   Note: we support multiple locations manually only.
observe the namespace scheduler to schedule the namespaces and objects to one instance of the location by setting the cluster.workloads.kcp.dev/<workload-cluster-id>="Sync" label.
- [x] https://github.com/kcp-dev/kcp/pull/829 LocationDomain workspace selector
- [x] https://github.com/kcp-dev/kcp/pull/829 the user will get the negotiated APIs in the other workspace X:
  - kubectl get APIBindings will show location-apis
  - kubectl get deployments will work

=== for p5 ===

- [x] https://github.com/kcp-dev/kcp/pull/1084 the syncer for the WorkloadCluster sees the objects from X and syncs them.
- [x] https://github.com/kcp-dev/kcp/pull/1125 allow serving compute from outside the org workspace of a user 

=== for p6 ===

- [x] 💣 restrict permission to service accounts
- [x] Placement object
- [x] Different workloads can be placed to different locations, where each gets an exact copy

=== stretch goals for p5, very likely p6 ===

- [x] Placement object
- ~[ ] Placement object with multiple locations~
- ~[ ] Placement strategies~

# Action Items

- [x] Scope the current demo as necessary to fit in prototype boundaries
- [x] https://github.com/kcp-dev/kcp/pull/829 Merge scheduling.kcp.dev/v1alpha1 API
- [x] Implement feature gates and hide half-finished feature behind a age
- [x] merge advanced scheduling PR https://github.com/kcp-dev/kcp/pull/942
- [x] merge virtual workspace PR https://github.com/kcp-dev/kcp/pull/754
  - [ ] **Follow-up:** unit test label selector in forwarding store
  - [ ] **Follow-up:** e2e test label selector filtering of virtual workspace
  - [ ] **Follow-up:** unit test apireconcile controller
  - [ ] **Follow-up:** investigate whether the upstream strategy has side-effects like increasing generation (which should be done on the server).
  - [ ] **Follow-up:** add extensive tests that the dynamic virtual workspace actually does what it should including checking validation.
- [x] https://github.com/kcp-dev/kcp/pull/1067switch syncer over to virtual workspace @davidfestal @jmprusi 
- [x] merge `WorkloadCluster.status.URLs` controller @jmprusi 
- [x] #1071
- [x] https://github.com/kcp-dev/kcp/pull/1084 merge namespace controller update to join the new workload+placement labels/annotations
- [x] https://github.com/kcp-dev/kcp/pull/1125
- [ ] doc and demo
 
=== 0.6.0 ===

- [x] https://github.com/kcp-dev/kcp/pull/1277 placement API.
- [x] https://github.com/kcp-dev/kcp/pull/1277 remove the workload cluster from the placement annotation keys.
- [x] https://github.com/kcp-dev/kcp/pull/1277 split apart the workload cluster selection for a location from the placement controller.
- [x] https://github.com/kcp-dev/kcp/pull/1277 placement controller to select location
- [x] auto-create a placement objects
- **Follow-ups**: e2es for
    - [x] multiple placements
    - [ ] draining with two clusters in the same location
    - [ ] overlapping clusters in two locations
    - [ ] overlapping locations in two placements
    - [ ] relabelling a WorkloadCluster that moves it to another location.

=== 0.8.0 ===

- [x] #1172
- [x] switch to UIDs in all workload cluster labels instead of `WorkloadCluster`. This also solves that `WorkloadClusters` are not unique in kcp between workspaces.
- [x] https://github.com/kcp-dev/kcp/issues/1777
- [x] https://github.com/kcp-dev/kcp/issues/1778: #1828 

=== stretch goal or 0.9.0 from here ===

- [ ] generalize locationdomain controller to support arbitrary resources, by using a dynamic informer (for that we need a way to use metadata GVR wildcard requests even for APIBindings).
- [ ] security-💣: protect scheduling annotations/labels such that not every user can set them.

**Comment by davidfestal** [comment]
Removed https://github.com/kcp-dev/kcp/issues/1779 and https://github.com/kcp-dev/kcp/issues/1888 from the EPIC here to include them in the newly-created EPIC about [Compute type Management](https://github.com/kcp-dev/kcp/issues/1895)

**Comment by davidfestal** [comment]
Action item "the user can see Location objects as projections (and aggregations?) of WorkloadClusters." has also been moved to the new EPIC about [Compute type Management](https://github.com/kcp-dev/kcp/issues/1895)

**Comment by davidfestal** [comment]
Removed the following action items from the current EPIC:
- coordination controller support and demo
-  Finish and merge Syncer virtual workspace transformations (and replace Syncer advanced scheduling feature by transformations)
- Reenable the splitter use-cases

to move them to the new EPIC about [Support for multiple SyncTargets syncing and coordination controllers](https://github.com/kcp-dev/kcp/issues/1898)
