### ISSUE TITLE
Advanced scheduling

### ISSUE THREAD

**Issue by jmprusi** [kcp-dev/kcp#914]
# Demo Objective

The objective of this epic is to enable the scheduling of a resource into multiple workloadclusters while allowing external controllers to control some stages of it, being able to apply backpressure/block deletion of resources. 

This demo also introduces an experimental annotation to apply jsonPatch diffs for a specific workloadcluster: `experimental.specdiff.workloads.kcp.dev/<first-workload-cluster-name>=<json-patch-changing-replicas-to-half>`

# Demo Steps

1. Create a workspace with multiple WorkloadClusters.
2. Create a namespace with the labels: 
```
cluster.workloads.kcp.dev/<first-workload-cluster-name>="Sync"
cluster.workloads.kcp.dev/<second-workload-cluster-name>="Sync".
``` 
3. Add a deployment with labels
```
cluster.workloads.kcp.dev/<first-workload-cluster-name>=""
cluster.workloads.kcp.dev/<second-workload-cluster-name>="".
```
And notice it is not synced.

4. Set deployment labels
```
cluster.workloads.kcp.dev/<first-workload-cluster-name>="Sync"
cluster.workloads.kcp.dev/<second-workload-cluster-name>="Sync".
```
and annotations:
```
experimental.specdiff.workloads.kcp.dev/<first-workload-cluster-name>=<json-patch-changing-replicas-to-half>
experimental.specdiff.workloads.kcp.dev/<second-workload-cluster-name>=<json-patch-changing-replicas-to-half>
```
Notice that the syncer sync the deployment to both clusters and applies both spec diffs.

5. Observe that the two syncers add unique finalizers `(syncer-<workload-cluster-name>)` to the deployment upstream.
6. Notice that both syncer sync JSON status into the annotation `experimental.status.workloads.kcp.dev/<workload-cluster-id>` instead of updating the actual status, and the syncer ignores that annotation in spec sync.
7. Set `finalizers.workloads.kcp.dev/<workload-cluster-id> = "controller1"` on the deployment.
8. Set `cluster.workloads.kcp.dev/<first-workload-cluster-name>="Delete"` on the deployment.
9. Observe that the finalizer blocks the deletion progress.
10. Delete the finalizer on the deployment.
11. Observe that the first cluster deletes the deployment downstream, removes its own (real upstream) finalizer from the deployment, and deletes the status annotation.
12. Also, observe that the first cluster increases replicas to the full number.
13. Notice that the syncer removes sets `cluster.workloads.kcp.dev/<first-workload-cluster-name>=""` as soon as the object is removed downstream, and the namespace scheduler does not change it back to `Delete`.

Adapted from the [KCP Demo Script - 0.4 document](https://docs.google.com/document/d/1LFb8ZwBblIiLQyCHa_u9WVemjSxprOTUaEaVUZ_HzDM/edit#)

# Action Items

- [x] Scope the current demo as necessary to fit in the prototype boundaries
- [ ] Contribute to final demo script and recording, or demo live in video or community call

# Stories

- [x] Support multicluster scheduling in the current namespace-scheduler (`cluster.internal.workloads.kcp.dev/<workload-cluster-id>`)
   - [x] unit tested
   - [x] e2e tested, part of https://github.com/kcp-dev/kcp/pull/1084
- [x] Add syncer finalizers implemenation
   - [x] unit tested 
   - [ ] ~~e2e tested~~ https://github.com/kcp-dev/kcp/issues/1193
- [x] Implement per location external  soft finalizers (finalizers.workloads.kcp.dev/<workload-cluster-id>)
   - [x] unit tested
   - [ ] ~~e2e tested~~ https://github.com/kcp-dev/kcp/issues/1193
- [x] Implement `experimental.status.workloads.kcp.dev/<workload-cluster-id>`
   - [x] unit tested
   - [x] e2e tested
- [x] Add support for `experimental.specdiff.workloads.kcp.dev`
   - [x] unit tested
   ~~- [ ] e2e tested~~ only experimental and to be replaced with transformations

**Comment by sttts** [comment]
Remaining e2e tasks moved to #1193.
