### ISSUE TITLE
Multi-Release-Epic: multi-workspace controller development

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#981]
# Stories
- [x] Add APIExport virtual workspace  - https://github.com/kcp-dev/kcp/pull/1132
    -  Find a way to let owner specify additional resources (e.g. secrets) that need to be included
    - [Future] Filter the resources so it’s not “all secrets” etc.
- [x] Add authorization checks for APIBindings https://github.com/kcp-dev/kcp/issues/1013
    - User using bound API can’t modify status, for example, i.e. the APIExport provider has to define what a user (even a workspace admin) can do at a maximum.
- [x] APIBinding CR deletion #846

===== up to here blockers for v0.5 =====

- [x] @ncdc Add controller to set the virtual workspace URLs on APIExport status #1155
- [x] #1151
    - Service account has permission to use it but not regular users

===== up to here must-have for shortly after v0.5 =====

- [X] ~Add cluster-aware clientset code-generator, generate for kcp, kubernetes #759~ Using custom roundtripper + context instead
    - ~Must work against upstream unmodified client-go, apimachinery, etc~ Using custom roundtripper + context instead
- [x] Restrict non-identity wildcard list/watch to internal kcp controllers
    - [x] Close out #545 when this is done

===== v0.8 =====
- [ ] Scoping client calls in KCP https://github.com/kcp-dev/kcp/issues/1490

===== v0.9 =====
- [ ] (Continued, see issue for details) Scoping client calls in KCP https://github.com/kcp-dev/kcp/issues/1490

===== v0.X =====

- [ ] Add cluster-aware shared informers + listers #209
- [ ] Add helper that can look at an APIExport, get its virtual workspace URL(s), and then construct a rest config to use for wildcard informers

**Comment by pweil-** [comment]
0.8 check in.  It is unclear what is to be delivered in the 0.8 milestone.  Can we specify in the description?

**Comment by pweil-** [comment]
updated to add #1490 and move unfinished, un-milestoned items to a separate list

**Comment by stevekuznetsov** [comment]
I've moved this to https://github.com/orgs/kcp-dev/projects/6/views/1?layout=board
